### ISSUE TITLE
Dealing with unstable neurons

### ISSUE THREAD

**Issue by refactoriel** [pillowlab/neuroGLM#11]
Hi all,

This is not exactly a problem with the software, but rather a general analysis question.

In our acute recordings we often have drift that leads to units appearing and disappearing during a recording session. That means that there is a set of units that were recorded in all trials but also a set of units that have limited, not necessarily overlapping, "lifetimes".
How would I deal with these unstable neurons? I cannot simply leave the spike trains for these units empty outside their lifetimes, since the unit is not merely silent but is not recorded from.

As a side note: is this repo still being maintained or should I switch to pillowlab/GLMspiketools?

Thanks, Daniel

**Comment by memming** [comment]
If you can easily detect when the units are present, you can fit only those time periods of data when the neuron is present. In this package, you can do so by using 'trials' structure to represent this discontinuity in observation (also known as censored time series).

**Comment by refactoriel** [comment]
Thanks for the super-fast reply @memming!
If I understand correctly, I can predict spike trains of unstable units.
But can I also use unstable units' spike trains as regressors to predict other spike trains?

**Comment by memming** [comment]
If you are trying to infer coupling, this is slightly more tricky. This is especially so if you have a lot of units that phases in and out. There's no easy way of giving a good Bayesian treatment of complex censored regressors using this package.

**Comment by jpillow** [comment]
Hi Daniel,

Thanks for your message!  I agree Memming: fitting GLM to a particular
neuron should be as simple as selecting trials for which the neuron's
spikes were recorded (since fitting is independent for each neuron), but
handling coupling filters from a neuron that fades in and out is much
trickier, since that involves censoring of a regressor.  We don't have a
good solution for that.

I'm not sure how actively Memming is maintaining neuroGLM, but people from
my group are certainly using it.  GLMspiketools is doesn't handle
trial-structured data, so that's the main advantage of this package.

best,
Jonathan

**Comment by refactoriel** [comment]
@memming @jpillow : thanks for the clarification!

So I'll do my best with the data at hand and hope that someone will come up with a solution for censored regressors ;)
